#!/usr/bin/env node
// Re-measures the three engines and rewrites the generated tables in
// expectations.js. Run with `npm run record` after intentionally changing what
// the demo does.
//
//   node test/record.mjs            # all three
//   node test/record.mjs chromium   # one
//
// test/verify.mjs then asserts a fresh measurement against what this wrote, so a
// change in real browser behaviour fails the test instead of silently rewriting
// the documentation.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { BROWSERS, CASES, EDITORS, measure } from "./harness.mjs";
import { LOAD_SENSITIVE_CELLS, classifyOutcome } from "../expectations.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const FILE = join(ROOT, "expectations.js");
const BEGIN = "// --- BEGIN GENERATED by test/record.mjs — do not edit by hand ---";
const END = "// --- END GENERATED ---";

const ROW_LABELS_SHORT = [];
const targets = process.argv.slice(2);
const names = targets.length ? targets : Object.keys(BROWSERS);

const tables = {};
const artifacts = {};
const errors = {};
const labels = CASES.map((testCase) => testCase.label);

for (const name of names) {
  process.stdout.write(`measuring ${name}… `);
  const result = await measure(name);
  if (result.rows.length !== CASES.length) {
    throw new Error(`${name}: measured ${result.rows.length} cases, expected ${CASES.length}`);
  }
  ROW_LABELS_SHORT.push(...result.rows.map((r) => r.label));
  const rows = result.rows.map((row, index) => {
    if (row.label !== labels[index]) {
      throw new Error(`${name}: case ${index} is "${row.label}", expected "${labels[index]}"`);
    }
    const entry = {};
    for (const kind of EDITORS) {
      const cell = row.by[kind];
      if (cell.error) {
        throw new Error(`${name} / ${row.label} / ${kind}: ${cell.error}`);
      }
      // "|" separated when the cell did not land on the same outcome every time.
      const measured = (cell.outcomes ?? [cell.text]).map(classifyOutcome);
      // Union in anything declared load-sensitive for this cell, since a repeated
      // measurement in one process does not reproduce another process's load.
      const declared = LOAD_SENSITIVE_CELLS[name]?.[row.label]?.[kind] ?? [];
      const outcomes = [...new Set([...measured, ...declared])].sort();
      for (const outcome of outcomes) {
        if (outcome.startsWith("unexpected:")) {
          throw new Error(`${name} / ${row.label} / ${kind}: ${outcome}`);
        }
      }
      entry[kind] = outcomes.join("|");
    }
    return entry;
  });
  tables[name] = rows;
  // Artifacts are sparse: only cells that actually contain one are recorded.
  artifacts[name] = rows.map((row, index) => {
    const entry = {};
    for (const kind of EDITORS) {
      const found = result.rows[index].by[kind].artifacts ?? [];
      if (found.length) {
        entry[kind] = found;
      }
    }
    return entry;
  });
  // Collapse the engine's own error wording: it is re-thrown per engine by the
  // same editor, but the messages differ.
  errors[name] = [...new Set(result.pageErrors.map((entry) => entry.split(": ")[0]))].sort();
  console.log("done");
}

const render = (value, indent) =>
  JSON.stringify(value, null, 2)
    .split("\n")
    .map((line, index) => (index === 0 ? line : indent + line))
    .join("\n");

const generated = [
  BEGIN,
  "",
  `export const EDITOR_KINDS = ${render(EDITORS, "")};`,
  "",
  `export const ROW_LABELS = ${render(labels, "")};`,
  "",
  `export const EXPECTATIONS = ${render(tables, "")};`,
  "",
  `export const ARTIFACTS = ${render(artifacts, "")};`,
  "",
  `export const PAGE_ERRORS = ${render(errors, "")};`,
  "",
  END,
].join("\n");

const current = await readFile(FILE, "utf8");
const start = current.indexOf(BEGIN);
const stop = current.indexOf(END);
if (start === -1 || stop === -1) {
  throw new Error(`could not find the GENERATED markers in ${FILE}`);
}
await writeFile(FILE, current.slice(0, start) + generated + current.slice(stop + END.length));

console.log(`\nwrote ${EDITORS.length} editors x ${labels.length} cases x ${names.length} engines into expectations.js`);
for (const name of names) {
  console.log(`\n${name}:`);
  const racy = [];
  for (const [index, row] of labels.entries()) {
    for (const kind of EDITORS) {
      if (tables[name][index][kind].includes("|")) {
        racy.push(`${row} / ${kind}: ${tables[name][index][kind]}`);
      }
    }
  }
  if (racy.length) {
    console.log("  non-deterministic cells (measured 3x each):");
    for (const line of racy) console.log(`    ${line}`);
  }
  for (const [index, label] of labels.entries()) {
    console.log(
      `  ${label.padEnd(50)} ` + EDITORS.map((k) => (tables[name][index][k] ?? "?").slice(0, 9).padEnd(10)).join(""),
    );
  }
  const withArtifacts = artifacts[name].flatMap((row, i) =>
    Object.entries(row).map(([kind, list]) => `${ROW_LABELS_SHORT[i]} / ${kind}: ${list.join(", ")}`),
  );
  for (const line of withArtifacts) {
    console.log(`  artifact: ${line}`);
  }
  console.log(`  page errors: ${errors[name].length ? errors[name].join(", ") : "none"}`);
}