#!/usr/bin/env node
// Re-measures the demo and rewrites the generated tables in expectations.js. Run with
// `npm run record` after intentionally changing what the demo does.
//
//   node test/record.mjs                                  # every engine, every context
//   node test/record.mjs chromium                         # one engine
//   node test/record.mjs --context=code-in-iframe         # one context
//   node test/record.mjs --context=editor-in-iframe --context=code-in-iframe chromium firefox webkit
//   node test/record.mjs --context=extension-isolated firefox
//
// What it cannot measure it says out loud, with the reason, and leaves the recorded table
// untouched rather than guessing. test/verify.mjs then asserts a fresh measurement against
// what this wrote, so a change in real browser behaviour fails the test instead of silently
// rewriting the documentation.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { CASES, EDITORS, editorsFor, measure, measureProbesOnly } from "./harness.mjs";
import { summariseProbes } from "../probes.js";
import { CONTEXT_ENGINES, CONTEXT_IDS, CONTEXT_LABELS, NOT_MEASURED, TOP } from "../contexts.js";
import {
  CONTEXT_LOAD_SENSITIVE_CELLS,
  LOAD_SENSITIVE_CELLS,
  classifyOutcome,
} from "../expectations.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const FILE = join(ROOT, "expectations.js");
const BEGIN = "// --- BEGIN GENERATED by test/record.mjs — do not edit by hand ---";
const END = "// --- END GENERATED ---";

const argv = process.argv.slice(2);
// Repeatable: --context=a --context=b measures exactly those two.
const onlyContexts = argv.filter((a) => a.startsWith("--context=")).map((a) => a.split("=")[1]);
const contextsToRecord = onlyContexts.length > 0 ? onlyContexts : CONTEXT_IDS;

const names = argv.filter((a) => !a.startsWith("--"));
const targets = names.length ? names : ["chromium", "firefox", "webkit"];
// --probes-only refreshes the probe tables without re-running the matrix, which is what
// you want after changing how probes are *described* rather than what they measure.
const probesOnly = argv.includes("--probes-only");

/**
 * What was already recorded, so a partial run does not erase the rest.
 *
 * Every existing table is carried forward as the base; `store` then replaces only the
 * engine/context cells it actually re-measured. The one time this was not done, a
 * probes-only run erased every recorded context matrix — hours of browser time — which
 * is why the merge is here and why it is tested below.
 */
const existing = await import("../expectations.js");
const tables = {
  top: { ...existing.EXPECTATIONS },
  ...Object.fromEntries(
    Object.entries(existing.CONTEXT_EXPECTATIONS).map(([contextId, engines]) => [
      contextId,
      { ...engines },
    ]),
  ),
};
const artifacts = { top: { ...existing.ARTIFACTS } };
const errors = { top: { ...existing.PAGE_ERRORS } };
const probes = { ...existing.CONTEXT_PROBES };
const contextArtifacts = { ...existing.CONTEXT_ARTIFACTS };
const contextErrors = { ...existing.CONTEXT_PAGE_ERRORS };

const skipped = [];

/** Turn one measurement into the recorded shape, per engine and context. */
function record(result, contextId, name) {
  if (result.rows.length !== CASES.length) {
    throw new Error(`${name} / ${contextId}: measured ${result.rows.length} cases, expected ${CASES.length}`);
  }
  const rows = result.rows.map((row, index) => {
    if (row.label !== CASES[index].label) {
      throw new Error(`${name} / ${contextId}: case ${index} is "${row.label}", expected "${CASES[index].label}"`);
    }
    const entry = {};
    for (const kind of editorsFor(name)) {
      const cell = row.by[kind];
      if (cell.error) throw new Error(`${name} / ${contextId} / ${row.label} / ${kind}: ${cell.error}`);
      // "|" separated when the cell did not land on the same outcome every time.
      const measured = (cell.outcomes ?? [cell.text]).map(classifyOutcome);
      // Union in anything declared load-sensitive for this cell, since a repeated
      // measurement in one process does not reproduce another process's load.
      const declared = [
        ...(LOAD_SENSITIVE_CELLS[name]?.[row.label]?.[kind] ?? []),
        ...(contextId === TOP
          ? []
          : (CONTEXT_LOAD_SENSITIVE_CELLS[contextId]?.[name]?.[row.label]?.[kind] ?? [])),
      ];
      const outcomes = [...new Set([...measured, ...declared])].sort();
      for (const outcome of outcomes) {
        if (outcome.startsWith("unexpected:")) {
          throw new Error(`${name} / ${contextId} / ${row.label} / ${kind}: ${outcome}`);
        }
      }
      entry[kind] = outcomes.join("|");
    }
    return entry;
  });
  // Artifacts are sparse: only cells that actually contain one are recorded.
  const artifactRow = rows.map((row, index) => {
    const entry = {};
    for (const kind of editorsFor(name)) {
      const found = result.rows[index].by[kind].artifacts ?? [];
      if (found.length) entry[kind] = found;
    }
    return entry;
  });
  // Collapse the editor's own error wording: it is re-thrown per engine by the same editor,
  // but the messages differ. Only the "where" prefix is kept.
  const pageErrors = [...new Set(result.pageErrors.map((entry) => entry.split(": ")[0]))].sort();
  return { rows, artifactRow, pageErrors };
}

function store(contextId, name, { rows, artifactRow, pageErrors }, result) {
  if (contextId === TOP) {
    tables.top[name] = rows;
    artifacts.top[name] = artifactRow;
    errors.top[name] = pageErrors;
    return;
  }
  tables[contextId] ??= {};
  tables[contextId][name] = rows;
  contextArtifacts[contextId] ??= {};
  contextArtifacts[contextId][name] = artifactRow;
  contextErrors[contextId] ??= {};
  contextErrors[contextId][name] = pageErrors;
  if (result.probes) {
    probes[contextId] ??= {};
    probes[contextId][name] = summariseProbes(result.probes.influenceRealm, result.probes.environment);
  }
}

for (const name of targets) {
  for (const contextId of contextsToRecord) {
    if (!(CONTEXT_ENGINES[contextId] ?? []).includes(name)) {
      skipped.push(`${name} / ${contextId}: ${NOT_MEASURED[contextId]?.[name] ?? "not covered"}`);
      continue;
    }
    if (probesOnly) {
      if (contextId === TOP) {
        // The baseline has no probe button: it *is* the reference realm the probes
        // compare every other context against.
        continue;
      }
      process.stdout.write(`probing ${name} / ${CONTEXT_LABELS[contextId].short}… `);
      const { pageErrors, probes: rawProbes } = await measureProbesOnly(name, contextId);
      // Only the probe tables are touched; the recorded matrix and its page errors stay
      // exactly as the full run left them.
      probes[contextId] ??= {};
      probes[contextId][name] = summariseProbes(rawProbes.influenceRealm, rawProbes.environment);
      if (contextErrors[contextId]?.[name]) {
        contextErrors[contextId][name] = [
          ...new Set([...contextErrors[contextId][name], ...pageErrors.map((e) => e.split(": ")[0])]),
        ].sort();
      }
      console.log("done");
      continue;
    }
    process.stdout.write(`measuring ${name} / ${CONTEXT_LABELS[contextId].short}… `);
    const result = await measure(name, contextId);
    store(contextId, name, record(result, contextId, name), result);
    console.log("done");
  }
}

// ---------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------
const contextTables = Object.fromEntries(Object.entries(tables).filter(([key]) => key !== TOP));
const contextArtifactTables = Object.fromEntries(Object.entries(contextArtifacts));

const render = (value, indent) =>
  JSON.stringify(value, null, 2)
    .split("\n")
    .map((line, index) => (index === 0 ? line : indent + line))
    .join("\n");

const generated = [
  BEGIN,
  "",
  `export const EDITOR_KINDS = ${render(EDITORS, "")};`,
  "",
  `export const ROW_LABELS = ${render(CASES.map((entry) => entry.label), "")};`,
  "",
  `export const EXPECTATIONS = ${render(tables.top, "")};`,
  "",
  `export const ARTIFACTS = ${render(artifacts.top, "")};`,
  "",
  `export const PAGE_ERRORS = ${render(errors.top, "")};`,
  "",
  `export const CONTEXT_EXPECTATIONS = ${render(contextTables, "")};`,
  "",
  `export const CONTEXT_PROBES = ${render(probes, "")};`,
  "",
  `export const CONTEXT_ARTIFACTS = ${render(contextArtifactTables, "")};`,
  "",
  `export const CONTEXT_PAGE_ERRORS = ${render(contextErrors, "")};`,
  "",
  END,
].join("\n");

const current = await readFile(FILE, "utf8");
const start = current.indexOf(BEGIN);
const stop = current.indexOf(END);
if (start === -1 || stop === -1) throw new Error(`could not find the GENERATED markers in ${FILE}`);
await writeFile(FILE, current.slice(0, start) + generated + current.slice(stop + END.length));

console.log(
  `\nwrote ${EDITORS.length} editors x ${CASES.length} cases for ` +
    `${Object.keys(contextTables).length + 1} contexts into expectations.js`,
);

// ---------------------------------------------------------------------
// Report: what each context changed, against the same-document baseline
// ---------------------------------------------------------------------
for (const contextId of Object.keys(contextTables)) {
  console.log(`\n${CONTEXT_LABELS[contextId].label}`);
  for (const name of Object.keys(contextTables[contextId])) {
    const baseline = tables.top[name];
    const here = contextTables[contextId][name];
    if (!baseline) continue;
    const kinds = editorsFor(name);
    const changed = [];
    for (const [index, label] of CASES.map((entry) => entry.label).entries()) {
      for (const kind of kinds) {
        if (here[index][kind] !== baseline[index][kind]) {
          changed.push(`${label} / ${kind}: ${baseline[index][kind]} → ${here[index][kind]}`);
        }
      }
    }
    const total = CASES.length * kinds.length;
    console.log(
      `  ${name}: ${total - changed.length} of ${total} cells identical to the same-document baseline`,
    );
    for (const line of changed) console.log(`    ${line}`);
  }
  for (const [name, values] of Object.entries(probes[contextId] ?? {})) {
    console.log(`  probes in ${name}:`);
    for (const [probe, value] of Object.entries(values)) {
      console.log(`    ${probe.padEnd(24)} ${value}`);
    }
  }
  for (const [name, list] of Object.entries(contextErrors[contextId] ?? {})) {
    console.log(`  page errors in ${name}: ${list.length ? list.join(", ") : "none"}`);
  }
}

if (skipped.length) {
  console.log("\nnot measured (and not guessed):");
  for (const line of skipped) console.log(`  ${line}`);
}